services:
  ai-app:
    build: .
    volumes:
      - ./:/app
    ports:
      - 8501:8501
    depends_on:
      - llm

  llm:
    provider:
      type: model
      options:
        model: ai/llama3.2
